### ISSUE TITLE
Delete Supplier 

### ISSUE THREAD

**Issue by Vedsaga** [Monofyi/Mobile#42]
To delete Supplier user have to click on `Delete ` icon.
![Screenshot_20210730_132605](https://user-images.githubusercontent.com/59083528/127627660-300e6160-fd44-4756-b945-2d73a239da7b.jpg)

Then we will ask them again for the confirmation
![Screenshot_20210730_134611](https://user-images.githubusercontent.com/59083528/127627766-99d3978e-64c2-4e5d-8ed2-3939120df081.jpg)

Once they confirm on `Delete` then they will delete that supplier from backend. 
![Screenshot_20210730_134316](https://user-images.githubusercontent.com/59083528/127627902-4566459d-df6e-4503-aed8-f7b8170fdff0.jpg)

**Comment by Vedsaga** [comment]
Slight change in Remove supplies, `Top Bar is now removed `. Screen recording of user interaction is attached for the future reference.


https://user-images.githubusercontent.com/59083528/127759813-377efd9e-70d2-482e-b723-db1b1f54d89a.mp4

**Comment by Vedsaga** [comment]
Just a small fix request Anna, so when I remove the supplier, sometime it's still visible in UI..


https://user-images.githubusercontent.com/59083528/128431243-86038847-b5dd-49ea-8748-12d3ca39d214.mp4

**Comment by arun-muralidharan** [comment]
> Just a small fix request Anna, so when I remove the supplier, sometime it's still visible in UI..

When we do these operations too fast, it takes a bit for the DB to update, but we are fetching the data again before it is updated. That's why you are seeing the data. We could add a delay before we send the next request, but that will mean longer loading state. It would be better to modify the cached list, and show the user that instead. This will need a bit of bloc restructuring; I'll get this done by tomorrow.

**Comment by Vedsaga** [comment]
No worries Anna 👍, I am just pointing out in hopes that we keep traces of these small thighs so incase we launch we would be aware of these issues before even users and we can quickly patch up.
